### PR TITLE
Step 4: Option to sort (Roheel)

### PR DESCRIPTION
**Pull request by roheelislam**
Please review my code and approve to merge in main branch

### CODE REVIEW

**Comment by ghost** [comment]
Hi @roheelislam,

Thanks for your changes.

Your file settings.json is relative to your setup and shouldn't need to be in the repository. (you can store that locally and not push to remote).

just had some thoughts on your code, What happens when a user selects yes but chooses an option that is not available?

**Review by ghost — APPROVED** [review]
Looks good for me @roheelislam.

I wil remove the /.vscode/settings.json as that is for your setup not and doesn't need to be stored in the repo.

**Comment by roheelislam** [comment]
> Hi @roheelislam,
> 
> Thanks for your changes.
> 
> Your file settings.json is relative to your setup and shouldn't need to be in the repository. (you can store that locally and not push to remote).
> 
> just had some thoughts on your code, What happens when a user selects yes but chooses an option that is not available?

it will display an error message ad again give some options to choose :)

**Review by BenjaminMain — APPROVED** [review]

**Comment by ghost** [comment]
Pull request has been approved by 2 - merging into main

**Pull request merged**
