### PR TITLE
first draft of sorter.py

### PR DESCRIPTION
**Pull request by bradcruick**
Used hardcoding and made a few assumptions here so this code will change. Will update the code once we know the output of the earlier steps. Also, need to add assertion statements to this.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @bradcruick,

Good work, looks good. 

I know that this is only dummy data something I would suggest, is adding the 'if __name__ == "__main__":' and moving the lines 4-6 into that condition. 

You can test the file by 'python app/custom_modules/sorter.py'. Yet when it is called by the main.py function the code in the above condition will not be executed.

Any chance we can do this? I can then approve for you.

**Comment by bradcruick** [comment]
> Hi @bradcruick,
> 
> Good work, looks good.
> 
> I know that this is only dummy data something I would suggest, is adding the 'if **name** == "**main**":' and moving the lines 4-6 into that condition.
> 
> You can test the file by 'python app/custom_modules/sorter.py'. Yet when it is called by the main.py function the code in the above condition will not be executed.
> 
> Any chance we can do this? I can then approve for you.

Hey @GizmoStudent,

Thanks for the suggestion, added in the most recent commit.

**Review by ghost — APPROVED** [review]
@bradcruick Looks good to me. Good Job.

Maybe something to note / add, when using the distance, your expecting a distance element in the payload.

But on a plus note Iv done some basic tests and passed with flying colours!

**Comment by roheelislam** [comment]
Hi bradcruick,

I am doing 

Step 4: Option to sort (Roheel)
Criteria - Work with Bradley to establish what the input and output should be sort by the corresponding criteria.
Current Status: (In Process)

**Comment by roheelislam** [comment]
am I doing the same thing as you :


def my_function():
    with open('/Users/Nouma/OneDrive/Academic/UoE/Systems Development 1/Assignment_2/group-assessment/app/data_files/crime_files/2020-01-devon-and-cornwall-street.csv', newline='') as csvfile:
        data = csv.DictReader(csvfile)
        print("\n\t\t---------------------------------")
        print("\t\t***CRIME TYPE***")
        print("\t\t---------------------------------\n")
        list = []
        for row in data:       
            list.append(row['Crime type'])
        list.sort(reverse=False)
        list = '\n'.join(list)
        print(list)

my_function()

**Pull request merged**
